### ISSUE TITLE
Addon Manager Config disappear after choosing windower directory.

### ISSUE THREAD

**Issue by comola** [Icydeath/ffxi-addon-manager#1]
Hi,

I have download your addon_manager and tryt o run it. When it ask for the windower path. I choose the location and the program shut off. Please help.

Thank you,

Comola

**Comment by Icydeath** [comment]
Just checking, are you running it as administrator?
I'll see if I can replicate the issue on my side as well to help troubleshoot.

**Comment by Icydeath** [comment]
might be missing some .net runtimes as well... maybe... idk its been awhile since I've had to change anything with the tool.

**Comment by Icydeath** [comment]
Also, try deleting (or rename it) ../addons/addon_manager/data/settings.xml file, maybe there is a mistake in the xml that is causing the program to poop itself.

**Comment by Icydeath** [comment]
lastly, here is the runtime you'll need if you don't already have it.
https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472

**Comment by comola** [comment]
I will try the runtime.

**Comment by comola** [comment]
It seem I already have installed that or a higher version.

**Comment by comola** [comment]
Still close after I choose the windwoer directory even I rename the setting.xml

**Comment by comola** [comment]
And yes I run with administrator

**Comment by Icydeath** [comment]
Hmm what is the directory path you are choosing exactly? Just wondering if its having a hard time with your specific path.

**Comment by comola** [comment]
D:\playonline\windower\

**Comment by Icydeath** [comment]
Might be a bug, I'm not sure. I'll try to replicate the issue by pointing to my D drive as well. Is that your actual ffxi install folder as well? Could be some kind of permission issues going on... Idk for sure but I will report back once I have done some testing.

**Comment by Icydeath** [comment]
Please try this:

1. **In ffxi**, run **//lua unload addon_manager**  or if you have it loaded on multiple chars run **//send @all lua unload addon_manager**

2. **Delete** the **data** folder in the addon_manager folder **or Cut & Paste** it to your desktop (just so you have a backup if you have any configurations you wanted to keep)
 
3. **Download** the attached zip file --> **Right click the .zip file** and **Select Properties**. If you see a checkbox called **Unblock** in the bottom right of the General tab go ahead and **toggle it and click apply**, then **click OK**. If its not there just ignore this step. 
 
4. **Extract or Copy & Paste** the **Addon Manager Config.exe**, **addon_manager.lua**, and **lua53.dll** from the zip into your **D:\playonline\windower\addons\addon_manager\** folder and overwrite any and all files when prompted.
 
5. **In ffxi**, run **//lua load addon_manager** (This will create the default settings file.)
 
6. Finally, **Run** the **...\addons\Addon Manager Config.exe** (you should not have to run it as admin, but its possible it is required due to your folder permissions or if windows just wants to a dbag ^.^)

If its working and you are multiboxing you can load it for your other characters using **//send @others lua load addon_manager**

Good luck and let me know how it goes!


Edit: oops forgot to attach it, my bad! Click download button at the top right of the page.
[Addon Manager Config](https://drive.google.com/file/d/1W0yAVJnEjss2lIMd_1_j4cnsZGDE7t8t/view?usp=sharing)

**Comment by comola** [comment]
It worked. Thank you

**Comment by Icydeath** [comment]
Glad to hear it!
